@startuml

abstract class AbstractFunction {
    - name : String
    - scope : String
    + createFunction() : BWFunction
    + createObjectFunction(BWObject) : BWObjectFunction
}
abstract class AbstractVariable {
    - name : String
    - toEvaluate : BWExpression
    + getVariable()
}
class BWClass {
    - name : String
    - functions : AbstractFunction[]
    + BWObject : createInstance()
}
interface BWExpression {
    + getValue() : BWObject
    + getIntValue() : int
    + getValueType() : String
}
interface BWInstruction {
    + run(Scope)
}
class BWFunction {
}
class BWInteger {
    - value : int
}
class BWObject {
    - bwClass : BWClass
    - variables : BWVariable[]
    - functions : BWFunction[]
    + callFunction(String) : BWObject
}
class BWObjectFunction {
    - object : BWObject
}
class BWVariable {
    - name : String
    - value : BWObject
    + getValue() : BWObject
    + getIntValue() : int
}
class Calculation {
    - leftSide : BWExpression
    - rightSide : BWExpression
}
class Condition {
    - toEvaluate : BWExpression
    - trueInstructions : BWInstruction[]
    - falseInstructions : BWInstruction[]
}
class Exit {
}
class Loop {
    - toEvaluate : BWExpression
    - instructions : BWInstruction[]
}
class PrintChar {
    - charValue : int
}
class PrintVariable {
    - variableName : String
}
class Program {
    - {static} instance : Program
    - functions : BWFunction[]
    - classes : BWClass[]
    - variables : BWVariable[]
    - instructions : BWInstruction[]
    --
    - Program()
    + {static} getInstance() : Program
    + callFunction(String)
    + run()
}
class Scope {
    - currentObject : BWObject
    - arguments : BWVariable[]
    + isInObject()
}
class VariableDeclaration {
    - variableName : String
    - targetValue : BWExpression
}

Program --> BWFunction
Program --> BWClass
Program --> BWVariable
Program --> BWInstruction

Scope --> BWObject
Scope --> BWVariable

BWClass --> AbstractFunction

BWObject --> BWClass
BWObject <--> BWObjectFunction
BWObject --> BWVariable

BWVariable --> BWObject

VariableDeclaration --> BWExpression

Calculation --> BWExpression

Condition --> BWExpression
Condition --> BWInstruction

Loop --> BWExpression
Loop --> BWInstruction

BWExpression ..|> BWInstruction
AbstractFunction ..|> BWExpression
BWFunction --|> AbstractFunction
BWObjectFunction --|> BWFunction
AbstractVariable ..|> BWExpression
BWVariable --|> AbstractVariable
BWInteger --|> BWObject

Calculation ..|> BWExpression

VariableDeclaration ..|> BWInstruction
PrintVariable ..|> BWInstruction
PrintChar ..|> BWInstruction
Exit ..|> BWInstruction
Condition ..|> BWInstruction
Loop ..|> BWInstruction

@enduml